### ISSUE TITLE
Beautiful work!

### ISSUE THREAD

**Issue by atinux** [IAMSDR/MyAuthenticator#1]
Just wanted to say that this is beautiful work!

I think you could add the Deploy to NuxtHub button directly with:

```md
[![Deploy to NuxtHub](https://hub.nuxt.com/button.svg)](https://hub.nuxt.com/new?repo=IAMSDR/MyAuthenticator)
```

You will only need to set your repository as a GitHub template in order to work.

One small feedback regarding the UI, when refreshing the page, the timer circle start from the beginning again, I think this can be fixed easily.

Again, thank you for this nice app ❤️

**Comment by IAMSDR** [comment]
Thank you so much for your feedback and support. 
I've added the direct Deploy to NuxtHub button and updated the dependencies to the latest version.
I'll also fix the timer reset issue and add more features in a future update.

Thanks again for your feedback ❤️
